### ISSUE TITLE
UnboundLocalError: local variable 'cleaned_paths' referenced before assignment

### ISSUE THREAD

**Issue by inaod568** [ewels/rich-codex#24]
I installed it with pip.
1. Running `rich-codex` gave this error: 
```bash
INFO     Trimming terminal output down to a minimum of 80                                                      
INFO     Searching 7 files                                                                                     
Traceback (most recent call last):
  File "/home/ina/.local/bin/rich-codex", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ina/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ina/.local/lib/python3.10/site-packages/rich_codex/cli.py", line 476, in main
    if len(cleaned_paths) > 0:
UnboundLocalError: local variable 'cleaned_paths' referenced before assignment
```
2. `rich-codex --help` works
3. `rich-codex --command dds --img-paths test.svg` worked and created a correct image, but gave the same error message at the end:
```bash
INFO     Trimming terminal output down to a minimum of 80                                                                                                               
INFO     Command:  dds                                                                                                                                                  
Command:  dds  Run? [y/n]: y
INFO     Saved: 'test.svg' (new image)                                                                                                                                  
INFO     Searching 7 files                                                                                                                                              
INFO     Saved 1 images ✨                                                                                                                                              
Traceback (most recent call last):
  File "/home/ina/.local/bin/rich-codex", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ina/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ina/.local/lib/python3.10/site-packages/rich_codex/cli.py", line 476, in main
    if len(cleaned_paths) > 0:
UnboundLocalError: local variable 'cleaned_paths' referenced before assignment

```

**Comment by ewels** [comment]
Ugh, need to add some tests 🤦🏻

**Comment by ewels** [comment]
Ok, should now be fixed. Just pushed a release `v1.2.0` with the fix (the `v1` tag will be bumped to point to this automatically).

**Comment by ewels** [comment]
Thank you for letting me know! Shout if you hit any other issues.

**Comment by inaod568** [comment]
Nice! 💪🏻 No problem, will do.
