### ISSUE TITLE
OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by i-oden** [ewels/rich-codex#44]
Using `rich-codex` as a github action. Ran it and all was fine. Ran it about a day or so later and now the action fails with this:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/bin/rich-codex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/rich_click/rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/rich_codex/cli.py", line 455, in main
    codex_obj.save_all_images()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/rich_codex/codex_search.py", line 410, in save_all_images
    img_obj.get_output()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/rich_codex/rich_img.py", line 398, in get_output
    self.run_command()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/rich_codex/rich_img.py", line 211, in run_command
    size = fcntl.ioctl(0, termios.TIOCGWINSZ, struct.pack("HHHH", 0, 0, 0, 0))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 25] Inappropriate ioctl for device
Error: Process completed with exit code 1.
```

**Comment by i-oden** [comment]
Oook turns out I had `>` and `<` on a line in one of my rst files and this is what produced this error. Nothing to do with `rich-click` at all, my bad!

**Comment by ewels** [comment]
The best kind of bug report! 😄
